djangocrud/urls.py
from django.contrib import admin
from django.urls import path
from tasks import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks_completed/', views.tasks_completed, name='tasks_completed'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('create_task/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>', views.task_detail, name='task_detail'),
    path('taks/<int:task_id>/complete', views.complete_task, name='complete_task'),
    path('tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
  title = models.CharField(max_length=200)
  club2 = models.TextField(max_length=200)
  fecha = models.TextField(max_length=201,null=True)  
  golesclub = models.TextField(max_length=200,default=0,blank=True, null=True)
  golesclub2 = models.TextField(max_length=200,default=0,blank=True, null=True)
  created = models.DateTimeField(auto_now_add=True)
  datecompleted = models.DateTimeField(null=True, blank=True)
  important = models.BooleanField(default=False)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.title + ' - ' + self.user.username

tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'club2', 'fecha', 'golesclub','golesclub2' ,'important']

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Task

from .forms import TaskForm

# Create your views here.


def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {"form": UserCreationForm})
    else:

        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.create_user(
                    request.POST["username"], password=request.POST["password1"])
                user.save()
                login(request, user)
                return redirect('tasks')
            except IntegrityError:
                return render(request, 'signup.html', {"form": UserCreationForm, "error": "Username already exists."})

        return render(request, 'signup.html', {"form": UserCreationForm, "error": "Passwords did not match."})


@login_required
def tasks(request):
    tasks = Task.objects.filter(user=request.user, datecompleted__isnull=True)
    return render(request, 'tasks.html', {"tasks": tasks})

@login_required
def tasks_completed(request):
    tasks = Task.objects.filter(user=request.user, datecompleted__isnull=False).order_by('-datecompleted')
    return render(request, 'tasks.html', {"tasks": tasks})


@login_required
def create_task(request):
    if request.method == "GET":
        return render(request, 'create_task.html', {"form": TaskForm})
    else:
        try:
            form = TaskForm(request.POST)
            new_task = form.save(commit=False)
            new_task.user = request.user
            new_task.save()
            return redirect('tasks')
        except ValueError:
            return render(request, 'create_task.html', {"form": TaskForm, "error": "Error creating task."})


def home(request):
    return render(request, 'home.html')


@login_required
def signout(request):
    logout(request)
    return redirect('home')


def signin(request):
    if request.method == 'GET':
        return render(request, 'signin.html', {"form": AuthenticationForm})
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'signin.html', {"form": AuthenticationForm, "error": "Username or password is incorrect."})

        login(request, user)
        return redirect('tasks')

@login_required
def task_detail(request, task_id):
    if request.method == 'GET':
        task = get_object_or_404(Task, pk=task_id, user=request.user)
        form = TaskForm(instance=task)
        return render(request, 'task_detail.html', {'task': task, 'form': form})
    else:
        try:
            task = get_object_or_404(Task, pk=task_id, user=request.user)
            form = TaskForm(request.POST, instance=task)
            form.save()
            return redirect('tasks')
        except ValueError:
            return render(request, 'task_detail.html', {'task': task, 'form': form, 'error': 'Error updating task.'})

@login_required
def complete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    if request.method == 'POST':
        task.datecompleted = timezone.now()
        task.save()
        return redirect('tasks')

@login_required
def delete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    if request.method == 'POST':
        task.delete()
        return redirect('tasks')

tasks/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Navbar</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a href="/" class="nav-link">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'tasks_completed' %}" class="nav-link"
            >Fechas Jugadas</a
          >
        </li>
        <li class="nav-item">
          <a href="{% url 'tasks' %}" class="nav-link">Fechas</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'create_task' %}" class="nav-link">Fechas Nuevas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="/signin" class="nav-link">Login</a>
        </li>
        <li class="nav-item">
          <a href="/signup" class="nav-link">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

tasks/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django CRUD</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    
  </head>
  <body>
    {% include '_navbar.html' %}
    
    {% block content %}
    {% endblock %}
  </body>
  
</html>

tasks/templates/create_task.html
{% extends 'base.html' %}

{% block content %}
<main class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4 mt-5">
      <form class="card card-body" action="/create_task/" method="POST">
        <h1>Nueva Fecha</h1>
      
        {{error}}
        {% csrf_token %}
        <!-- {{form}} -->
        <div class="mb-3">
          <label for="title">Equipo1 </label>
          <input
            type="text"
            name="title"
            id="title"
            class="form-control"
            placeholder="Write your title"
          />
        </div>

        <div class="mb-3">
          <label for="club2">Equipo2 </label>
          <input
            type="text"
            name="club2"
            id="club2"
            class="form-control"
            placeholder="Confirm your club2"
          />
        </div>
        <div class="mb-3">
          <label for="fecha">Fecha </label>
          <input
            type="number"
            name="fecha"
            id="fecha"
            class="form-control"
            placeholder="Confirm your fecha"
          />
        </div>
        <!-- <div class="mb-3">
          <label for="golesclub">Confirm your Password: </label>
          <textarea name="golesclub" cols="40" rows="10" maxlength="200" required="" id="id_golesclub">0</textarea>
        </div>
        <div class="mb-3">
          <label for="golesclub2">Confirm your Password: </label>
          <input
            type="text"
            name="golesclub2"
            id="golesclub2"
            class="form-control"
            placeholder="Confirm your club2"
          />
        </div> -->

        
      
        <button class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
</main>


{% endblock %}

tasks/templates/home.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <h1>Home</h1>
</div>

{% endblock %}

tasks/templates/signin.html
{% extends "base.html" %}

{% block content %}

<main class="container">
  <div class="row">
    <section class="col-md-4 offset-md-4 mt-5">
      <form action="/signin/" class="card card-body" method="POST">
        <h1 class="text-center">Signin</h1>

        <p>
        {{error}}
        </p>
        {% csrf_token %}

        <div class="mb-3">
          <label for="username">Username: </label>
          <input
            type="text"
            name="username"
            id="username"
            class="form-control"
            placeholder="Write your username"
          />
        </div>

        <div class="mb-3">
          <label for="password">Password: </label>
          <input
            type="password"
            name="password"
            id="password"
            class="form-control"
            placeholder="Write your password"
          />
        </div>

        <button class="btn btn-primary">
          Signin
        </button>
      </form>
    </section>
  </div>
</main>



{% endblock %}

tasks/templates/signup.html
{% extends 'base.html' %} {% block content %}

<main class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4 mt-5">
      <form method="POST" class="card card-body">
        <h1 class="text-center">Signup</h1>
        {{error}} {% csrf_token %}

        <div class="mb-3">
          <label for="username">Username: </label>
          <input
            type="text"
            name="username"
            id="username"
            class="form-control"
            placeholder="Write your username"
          />
        </div>

        <div class="mb-3">
          <label for="password1">Password: </label>
          <input
            type="password"
            name="password1"
            id="password1"
            class="form-control"
            placeholder="Write your password"
          />
        </div>

        <div class="mb-3">
          <label for="password2">Confirm your Password: </label>
          <input
            type="password"
            name="password2"
            id="password2"
            class="form-control"
            placeholder="Confirm your Password"
          />
        </div>

        <button btn btn-primary>Signup</button>
      </form>
    </div>
  </div>
</main>
{% endblock %}

tasks/templates/task_detail.html
{% extends 'base.html' %}

{% block content %}



<main class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 py-5">
      <form class="card card-body" method="POST">
        {{error}}
        {% csrf_token %}
        <div class="mb-3">
          <label for="title">Equipo1 </label>
            <textarea            
            name="title"
            id="title"
            class="form-control">{{task.title}}
          </textarea>
        </div>

        <div class="mb-3">
          <label for="club2">Equipo2 </label>
          <textarea            
           name="club2"
          id="club2"
          class="form-control">{{task.club2}}
        </textarea>
        </div>
        <div class="mb-3">
          <label for="fecha">Fecha </label>
          <textarea            
           name="fecha"
          id="fecha"
          class="form-control">{{task.fecha}}
        </textarea>
        </div>
        <div class="mb-3">
          <label for="golesclub">Goles {{task.title}} </label>
          <input
            type="number"
            name="golesclub"
            id="golesclub"
            class="form-control"
            placeholder={{task.golesclub}}
            {{task.golesclub}}>
        </div> 
        <div class="mb-3">
          <label for="golesclub">Goles {{task.club2}} </label>
          <input
            type="number"
            name="golesclub2"
            id="golesclub2"
            class="form-control"
            placeholder= {{task.golesclub2}}
            
            {{task.golesclub2}}>
        </div> 
      
        
      
        <button class="btn btn-primary">Update</button>
        
      </form>
      
      <form class="card card-body" action="{% url 'complete_task' task.id %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-primary" >
          complete
        </button>
      </form>
      
      <form class="card card-body" action="{% url 'delete_task' task.id %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-primary">
          delete
        </button>
      </form>
    </div>
  </div>
</main>


{% endblock %}

tasks/templates/tasks.html
{% extends 'base.html' %} {% block content %}

<main class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 py-5">
      <h1 class="text-center ">Fechas</h1>

      <ul class="list-group">

        {% for task in tasks %}
        <a class="list-group-item " href="{% url 'task_detail' task.id %}">

            {% if task.important %}
            <strong>{{task.title}}</strong>   
            {% else %} 
            <div class="container text-center">
              <div class="row align-items-start">
                <div class="col">
                  {{task.fecha}}
                </div>
                <div class="col">
                  {{task.title}}
                </div>
                <div class="col">
                  VS
                </div>
                <div class="col">
                  {{task.club2}}
                </div>
              </div>
            </div>

                  

            

             

            {% endif %}

          <p>{{task.description}}</p>

          {{task.datecompleted|date:'M j Y:i'}}

        </a>
        {% endfor %}
      </ul>
      
    </div>
  </div>
</main>

{% endblock %}